import Image from "next/image";
import Link from "next/link";
import { QuoteForm } from "@/components/lead/QuoteForm";
import { Icon } from "@/components/ui/Icon";
import {
  FaqSection,
  ReferralDisclosureStrip,
  Section,
  SectionDivider,
} from "@/components/marketing/sections";
import {
  CostTable,
  InPageNav,
  KeyFacts,
  OptionsList,
  PrepColumns,
  RelatedServices,
  ScopeColumns,
  ServiceHero,
  Timeline,
} from "@/components/marketing/service-sections";
import {
  MayInclude,
  ServiceCtaBand,
  ServiceDisclosureBlock,
} from "@/components/marketing/service-detail-sections";
import type { ServiceDetail } from "@/content/service-details";
import {
  publishedServices,
  type ServiceRecord,
  type ServiceSectionId,
} from "@/content/services";
import {
  OUT_OF_AREA_POSTAL_CODE,
  serviceAreaOptions,
} from "@/content/locations";
import { site } from "@/lib/env";

/**
 * Each service page carries photographs of its own work. These used to be a
 * single shared driveway photo, which is how a patio page ends up closing on
 * somebody else's garage.
 */
const SERVICE_DETAIL_IMAGES: Record<string, { src: string; alt: string }> = {
  "concrete-driveways": { src: "/images/services/concrete-driveways/concrete-driveways-detail.webp", alt: "Driveway edge pitched away from the lawn with a gravel drainage margin" },
  "concrete-patios": { src: "/images/services/concrete-patios/concrete-patios-detail.webp", alt: "Plain concrete patio slab at the rear of a single story brick home" },
  "concrete-slabs": { src: "/images/services/concrete-slabs/concrete-slabs-detail.webp", alt: "Concrete pad still sitting inside its timber forms on an open lot" },
  "concrete-repair": { src: "/images/services/concrete-repair/concrete-repair-detail.webp", alt: "Settled concrete walkway slab with a cracked, lifted edge" },
};

/**
 * Photograph for the Process section, keyed by service. Every service carries
 * one, following the repair page as master: a service-specific work shot
 * above the timeline. Interim generated bytes for driveways, patios and
 * slabs; owner-supplied real photographs remain the endpoint.
 */
const SERVICE_PROCESS_IMAGES: Record<string, { src: string; alt: string }> = {
  "concrete-driveways": {
    src: "/images/services/concrete-driveways/concrete-driveways-process.webp",
    alt: "Wet concrete pouring from a mixer chute into timber forms for a residential driveway, with a screed board resting across the forms",
  },
  "concrete-patios": {
    src: "/images/services/concrete-patios/concrete-patios-process.webp",
    alt: "Stone-pattern stamping mats laid on a freshly poured patio with hand trowels, a mallet and a bucket beside the forms",
  },
  "concrete-slabs": {
    src: "/images/services/concrete-slabs/concrete-slabs-process.webp",
    alt: "Freshly poured concrete slab inside timber forms with a bull float resting on its surface, gravel and tools alongside",
  },
  "concrete-repair": {
    src: "/images/services/concrete-repair/concrete-repair-process.webp",
    alt: "Worker cutting into a concrete slab with a handheld cut off saw, throwing up a cloud of dust beside a chain link fence",
  },
};

const MAIN_NAV_LABELS: Record<ServiceSectionId, string> = {
  scope: "What's covered",
  options: "Options",
  process: "Process",
  cost: "What drives cost",
  prepare: "Prepare",
};

export interface LocalIntro {
  eyebrow: string;
  title: string;
  blocks: { heading: string; body: string }[];
}

/**
 * The single master template for every service page and every
 * location/service page. Same sections, same order, same components, same
 * spacing everywhere; only the title, the service/city-specific text and the
 * image differ between pages.
 *
 * Location/service pages pass `localIntro` (their city-specific text) which
 * renders as the lead section ahead of the shared master sections. Service
 * hubs pass null and start directly on the master sections.
 */
export function ServicePageTemplate({
  service,
  detail,
  breadcrumbs,
  cityLabel,
  h1,
  summary,
  heroImage = null,
  keyFacts,
  localIntro = null,
  faqTitle,
  faqs,
  faqName,
  relatedServices,
  relatedBasePath,
  relatedTitle,
  ctaTitle,
  ctaBody,
  defaultServiceSlug,
  callCardTitle,
  callCardBody,
}: {
  service: ServiceRecord;
  detail: ServiceDetail;
  breadcrumbs: React.ReactNode;
  cityLabel: string;
  h1: string;
  summary: string;
  /**
   * Hero photo override. Location/service pages pass their own distinct
   * photograph; hubs omit it and use the service hero.
   */
  heroImage?: { src: string; alt: string } | null;
  keyFacts: { label: string; value: string }[];
  localIntro?: LocalIntro | null;
  faqTitle: string;
  faqs: { question: string; answer: React.ReactNode }[];
  faqName: string;
  relatedServices: readonly ServiceRecord[];
  relatedBasePath?: string;
  relatedTitle: string;
  ctaTitle: string;
  ctaBody: string;
  defaultServiceSlug?: string;
  callCardTitle: string;
  callCardBody: string;
}) {
  const heroService = heroImage
    ? { ...service, image: heroImage.src, imageAlt: heroImage.alt }
    : service;

  const navItems = [
    ...service.sectionOrder.map((id) => ({ id, label: MAIN_NAV_LABELS[id] })),
    { id: "quote-form", label: "Get a quote" },
    { id: "faq", label: "FAQ" },
  ];

  return (
    <>
      <ServiceHero
        breadcrumbs={breadcrumbs}
        service={heroService}
        cityLabel={cityLabel}
        h1={h1}
        summary={summary}
      />
      <KeyFacts facts={keyFacts} />
      <ReferralDisclosureStrip />
      <InPageNav items={navItems} />

      <div className="container-page">
        <div className="grid gap-6 lg:grid-cols-12 lg:gap-12">
          {/* ---------------------------------------------------- Main column */}
          <div className="min-w-0 lg:col-span-7 xl:col-span-8">
            {localIntro ? (
              <section className="scroll-mt-36 py-12 md:py-20">
                <p className="eyebrow flex">{localIntro.eyebrow}</p>
                <h2 className="h2 mt-4">{localIntro.title}</h2>
                <div className="mt-8 max-w-prose space-y-6">
                  {localIntro.blocks.map((block) => (
                    <div key={block.heading}>
                      <h3 className="text-[22px] font-semibold leading-snug">
                        {block.heading}
                      </h3>
                      <p className="mt-1.5 text-[16px] leading-relaxed text-[color:var(--color-muted)]">
                        {block.body}
                      </p>
                    </div>
                  ))}
                </div>
              </section>
            ) : null}

            {service.sectionOrder.map((id, index) => {
              /*
               * The first master section carries no top rule only when no
               * local intro precedes it; otherwise every master section is
               * separated by one.
               */
              const first = index === 0 && !localIntro;
              const cls = first
                ? "scroll-mt-36 py-12 md:py-20"
                : "scroll-mt-36 border-t py-12 md:py-20";
              const style = first
                ? undefined
                : { borderColor: "var(--color-line-soft)" };

              if (id === "scope") {
                return (
                  <section key={id} id="scope" className={cls} style={style}>
                    <p className="eyebrow flex">Scope</p>
                    <h2 className="h2 mt-4">{service.headings.scope}</h2>
                    <p className="lede mt-4 max-w-prose">{service.summary}</p>
                    <div className="mt-8">
                      <ScopeColumns
                        covered={service.covered}
                        outOfScope={service.outOfScope}
                      />
                    </div>
                  </section>
                );
              }

              if (id === "options") {
                return (
                  <section key={id} id="options" className={cls} style={style}>
                    <p className="eyebrow flex">Specification</p>
                    <h2 className="h2 mt-4">{service.headings.options}</h2>
                    <p className="lede mt-4 max-w-prose">
                      {service.optionsLead}
                    </p>
                    <div className="mt-8">
                      <OptionsList options={service.options} />
                    </div>
                  </section>
                );
              }

              if (id === "process") {
                return (
                  <section key={id} id="process" className={cls} style={style}>
                    <p className="eyebrow flex">Process</p>
                    <h2 className="h2 mt-4">{service.headings.process}</h2>
                    <p className="lede mt-4 max-w-prose">
                      {service.processLead}
                    </p>
                    {SERVICE_PROCESS_IMAGES[service.slug] ? (
                      <Image
                        src={SERVICE_PROCESS_IMAGES[service.slug].src}
                        alt={SERVICE_PROCESS_IMAGES[service.slug].alt}
                        width={1100}
                        height={741}
                        sizes="(min-width: 1024px) 48rem, 100vw"
                        className="mt-8 h-56 w-full rounded-[12px] object-cover md:h-64"
                      />
                    ) : null}
                    <div className="mt-8">
                      <Timeline phases={service.process} />
                    </div>
                  </section>
                );
              }

              if (id === "cost") {
                return (
                  <section key={id} id="cost" className={cls} style={style}>
                    <p className="eyebrow flex">Pricing</p>
                    <h2 className="h2 mt-4">{service.headings.cost}</h2>
                    <p className="lede mt-4 max-w-prose">{service.costLead}</p>
                    <div className="mt-8">
                      <CostTable rows={service.costFactors} />
                    </div>
                  </section>
                );
              }

              return (
                <section key={id} id="prepare" className={cls} style={style}>
                  <p className="eyebrow flex">Preparation</p>
                  <h2 className="h2 mt-4">{service.headings.prepare}</h2>
                  <div className="mt-8">
                    <PrepColumns
                      checklist={service.prepChecklist}
                      questions={service.quoteQuestions}
                    />
                  </div>
                </section>
              );
            })}

            {/*
              Routing note, set as a card row rather than a bare paragraph. The
              words are unchanged; the unstyled single-paragraph section read as
              a stray line between two rules instead of an intentional element.
            */}
            <section
              aria-label="Routing checks"
              className="scroll-mt-36 border-t py-10"
              style={{ borderColor: "var(--color-line-soft)" }}
            >
              <div className="card flex items-start gap-3 p-5">
                <span
                  className="mt-0.5 shrink-0"
                  style={{ color: "var(--color-accent)" }}
                >
                  <Icon name="shield" className="h-[18px] w-[18px]" />
                </span>
                <p className="text-[14.5px] leading-relaxed text-[color:var(--color-muted)]">
                  Before anything is sent we check written coverage, project
                  type, an active referral agreement and current capacity.{" "}
                  <Link
                    href="/how-it-works"
                    className="font-semibold underline underline-offset-4"
                    style={{ color: "var(--color-accent)" }}
                  >
                    How a request is checked and routed
                  </Link>
                  .
                </p>
              </div>
            </section>
          </div>

          {/* ------------------------------------------------------- Sidebar */}
          <aside className="order-first min-w-0 lg:order-none lg:col-span-5 xl:col-span-4">
            <div className="lg:sticky lg:top-[7.5rem] lg:pt-2 lg:pb-12">
              <QuoteForm
                services={publishedServices.map((s) => ({
                  slug: s.slug,
                  name: s.name,
                }))}
                defaultServiceSlug={defaultServiceSlug}
                serviceAreas={serviceAreaOptions}
                outOfAreaValue={OUT_OF_AREA_POSTAL_CODE}
                consentVersion={site.consentVersion}
                fallbackDisplay={site.phoneDisplay}
                fallbackE164={site.phoneE164}
              />
              <div className="card mt-4 p-5">
                <p className="text-sm font-semibold">{callCardTitle}</p>
                <p className="mt-1.5 text-sm text-[color:var(--color-muted)]">
                  {callCardBody}
                </p>
                <a
                  href={`tel:${site.phoneE164}`}
                  className="btn btn-secondary mt-4 w-full"
                >
                  Call {site.phoneDisplay}
                </a>
              </div>
            </div>
          </aside>
        </div>
      </div>

      <SectionDivider />

      <section id="may-include" className="scroll-mt-32">
        <Section
          backgroundImage={SERVICE_DETAIL_IMAGES[service.slug]}
          eyebrow="Include"
          title={`What a ${service.projectNoun} project may include`}
        >
          <MayInclude
            items={detail.mayInclude}
            serviceName={service.projectNoun}
          />
        </Section>
      </section>

      <ServiceDisclosureBlock />

      <section id="faq" className="scroll-mt-32">
        <Section compact eyebrow="FAQ" title={faqTitle}>
          <FaqSection faqs={faqs} name={faqName} />
        </Section>
      </section>

      <SectionDivider />

      <Section compact eyebrow="Other services" title={relatedTitle}>
        <RelatedServices
          services={relatedServices}
          currentSlug={service.slug}
          basePath={relatedBasePath}
        />
      </Section>

      <ServiceCtaBand title={ctaTitle} body={ctaBody} />
    </>
  );
}
